title: Claudia Gonzalez # your name (or website title) here
logo: "/images/IMG_1912.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing my masters in Geospatial Technologies at the University of Oklahoma. I am a detail-oriented and multidisciplinary professional with experience in laboratory science and geospatial technologies. I am interested in integrating data-driven insights with real-world applications, particularly in urban planning or environmental sustainability. I am seeking opportunities where I can apply my expertise in GIS and spatial analysis skills to projects  that make an impact in conservation and environmental planning. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/claudiaj-gonzalez/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
